### ISSUE TITLE
Set out only 9 Instances in your .designspace

### ISSUE THREAD

**Issue by davelab6** [jeremytribby/ATTN#1]
Please only generate 9 instances per family, because CSS3 only supports 9 per family (100 .. 900) 

Also if you haven't seen it, do review the http://www.impallari.com/familysteps/ (http://typedrawers.com/discussion/205/family-stem-weights-calculator)

**Comment by jeremytribby** [comment]
Done & done :) I'd seen Impallari's formula but hadn't considered why it maxed out at 9.

**Comment by davelab6** [comment]
You can of course do more, the Fira fonts at 4.x onwards have done so, but with your masters I think 9 is enough; you want to give users enough distance between instances to be useful at creating contrast :)

**Comment by jeremytribby** [comment]
9 seems fine, and of course I have to symbolically align myself with CSS! :) now that I've had some time to sit with the idea I may even further reduce until there's a black master... we'll see!
